### ISSUE TITLE
TLAS Bounding Box Incorrect, and always miss

### ISSUE THREAD

**Issue by maxi201567** [GPUOpen-Tools/radeon_raytracing_analyzer#5]
![image](https://github.com/GPUOpen-Tools/radeon_raytracing_analyzer/assets/14181539/8f584d7f-2209-42eb-b984-4d2ecd02dbe0)
(Vulkan 1.3, 6600XT)
My TLAS Sphere And Box always have incorrect bounding box after build. And there is no any error log. How can i fix this problem.

**Comment by calper-ql** [comment]
Hi, is "always miss" as in that the rays are missing in your application or in the RRA traversal counters ? Also, it'd be nice to take a look at the trace if you could upload it for sharing somehow.

**Comment by maxi201567** [comment]
[20231030-221924.zip](https://github.com/GPUOpen-Tools/radeon_raytracing_analyzer/files/13210943/20231030-221924.zip)
 Thanks！

**Comment by calper-ql** [comment]
> [20231030-221924.zip](https://github.com/GPUOpen-Tools/radeon_raytracing_analyzer/files/13210943/20231030-221924.zip) Thanks！

Ok, I looked into the scene and I can confirm that the BLASes that the instances are pointing to look ok. However, the bounds were not properly stored. To me it looks like the TLAS build was started before the BLAS build finished. Can you confirm that you have a barrier between your BLAS builds and TLAS build ? To confirm you could capture a Radeon GPU Profiler (RGP) trace. When you open the trace there you can find your TLAS build and see if it overlaps with the BLAS.

**Comment by calper-ql** [comment]
@maxi201567 For reference, adding something like this after your BLAS build command might fix the issue:
```    
    VkMemoryBarrier barrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};
    barrier.srcAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR;
    barrier.dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR;
    vkCmdPipelineBarrier(
        cmd,
        VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
        VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
        0,
        1,
        &barrier,
        0,
        nullptr,
        0,
        nullptr);```

**Comment by maxi201567** [comment]
> @maxi201567 For reference, adding something like this after your BLAS build command might fix the issue:
> 
> ```
>     VkMemoryBarrier barrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};
>     barrier.srcAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR;
>     barrier.dstAccessMask = VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR;
>     vkCmdPipelineBarrier(
>         cmd,
>         VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
>         VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
>         0,
>         1,
>         &barrier,
>         0,
>         nullptr,
>         0,
>         nullptr);```
> ```

I really appreciate it!!
